In [9]:
import numpy as n
import pandas as pd 
import matplotlib.pyplot as plt 
from sklearn.neighbors import KNeighborsClassifier as k 
from sklearn.model_selection import train_test_split as t
from sklearn.preprocessing import StandardScaler as s

In [10]:
data=pd.read_csv('iris1.csv')
data.head(5)

sepal length in cm    sepal width in cm      petal length in cm  \
0                 5.1                  3.5                     1.4   
1                 4.9                  3.0                     1.4   
2                 4.7                  3.2                     1.3   
3                 4.6                  3.1                     1.5   
4                 5.0                  3.6                     1.4   

        petal width in cm       class:  
0                     0.2  Iris-setosa  
1                     0.2  Iris-setosa  
2                     0.2  Iris-setosa  
3                     0.2  Iris-setosa  
4                     0.2  Iris-setosa

In [33]:
x=data.iloc[:,:4].values
y=data.iloc[:,-1].values
x_train,x_test,y_train,y_test=t(x,y,test_size=0.2)
print(len(x_train))
print(len(x_test))

120
30


In [34]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)

x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [39]:
obj=k(n_neighbors=3)
obj=obj.fit(x_train,y_train)
y_pred=obj.predict(x_test)
from sklearn.metrics import classification_report as cr ,confusion_matrix as cm ,accuracy_score as a
result=asp(y_pred,y_test)
print(f'the accuracy_score is \n {result}')
result1=cr(y_test,y_pred)
print(f'the classification_report is \n{result1}')
result2=cm(y_test,y_pred)
print(f'the confusion metrix  is \n{result2}')      

the accuracy_score is 
 0.9333333333333333
the classification_report is 
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         6
Iris-versicolor       0.94      0.94      0.94        16
 Iris-virginica       0.88      0.88      0.88         8

       accuracy                           0.93        30
      macro avg       0.94      0.94      0.94        30
   weighted avg       0.93      0.93      0.93        30

the confusion metrix  is 
[[ 6  0  0]
 [ 0 15  1]
 [ 0  1  7]]


In [40]:
data1=pd.read_csv('wine.CSV')
data1.head(4)

A      B     C     D     E    F     G     H     I     J     K     L     M  \
0  1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1  1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2  1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3  1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   

      N  
0  1065  
1  1050  
2  1185  
3  1480

In [42]:
x=data1.iloc[:,:13].values
y=data1.iloc[:,-1].values
x_train,x_test,y_train,y_test=t(x,y,test_size=0.2)
print(len(x_train))
print(len(x_test))

142
36


In [44]:
obj1=s()
obj1.fit(x_train)
x_train=obj1.transform(x_train)
x_test=obj1.transform(x_test)
obb=k(n_neighbors=5)
obb=obb.fit(x_train,y_train)
y_pred=obb.predict(x_test)
result1=asp(y_test,y_pred)
print(f'the accuracy_score is \n {result1}')
result2=cr(y_test,y_pred)
print(f'the classification_report  is \n {result2}')
result3=cm(y_test,y_pred)
print(f'the confusion metrics  is \n {result3}')


the accuracy_score is 
 0.0
the classification_report  is 
               precision    recall  f1-score   support

         342       0.00      0.00      0.00       1.0
         352       0.00      0.00      0.00       1.0
         372       0.00      0.00      0.00       1.0
         380       0.00      0.00      0.00       1.0
         415       0.00      0.00      0.00       1.0
         434       0.00      0.00      0.00       1.0
         466       0.00      0.00      0.00       1.0
         470       0.00      0.00      0.00       1.0
         500       0.00      0.00      0.00       0.0
         510       0.00      0.00      0.00       1.0
         515       0.00      0.00      0.00       1.0
         560       0.00      0.00      0.00       1.0
         564       0.00      0.00      0.00       1.0
         600       0.00      0.00      0.00       1.0
         620       0.00      0.00      0.00       1.0
         625       0.00      0.00      0.00       0.0
         640       0.

c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\metrics\classification.py:1439: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
