In [1]:
import pandas as pd
import numpy as np
data=pd.read_csv('bill.csv')
d=pd.DataFrame(data)
d.head(5)

Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [15]:
x=d.iloc[:,:4].values
y=d.iloc[:,-1].values

In [16]:
from sklearn.model_selection import train_test_split as t
x_train,x_test,y_train,y_test=t(x,y,test_size=0.2,random_state=42)
print(len(x_train))
print(len(x_test))

1097
275


In [17]:
from sklearn.svm import SVC
obj=SVC(kernel='linear')
obj.fit(x_train,y_train)
y_pred=obj.predict(x_test)
from sklearn.metrics import classification_report as cr, confusion_matrix as cm,accuracy_score as asp
result=cr(y_test,y_pred)
result1=cm(y_test,y_pred)
result2=asp(y_test,y_pred)
print(f' the classification_report is \n{result}') 
print(f'the confusion_matrix is \n {result1}')
print(f'the accuracy_score is \n {result2}')

 the classification_report is 
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       148
           1       0.98      0.98      0.98       127

    accuracy                           0.99       275
   macro avg       0.99      0.99      0.99       275
weighted avg       0.99      0.99      0.99       275

the confusion_matrix is 
 [[146   2]
 [  2 125]]
the accuracy_score is 
 0.9854545454545455


In [5]:
obj=SVC(kernel='poly')
obj.fit(x_train,y_train)
y_pred=obj.predict(x_test)
from sklearn.metrics import classification_report as cr, confusion_matrix as cm,accuracy_score as asp
result=cr(y_test,y_pred)
result1=cm(y_test,y_pred)
result2=asp(y_test,y_pred)
print(f' the classification_report is \n{result}') 
print(f'the confusion_matrix is \n {result1}')
print(f'the accuracy_score is \n {result2}')

 the classification_report is 
              precision    recall  f1-score   support

           0       1.00      0.99      1.00       148
           1       0.99      1.00      1.00       127

    accuracy                           1.00       275
   macro avg       1.00      1.00      1.00       275
weighted avg       1.00      1.00      1.00       275

the confusion_matrix is 
 [[147   1]
 [  0 127]]
the accuracy_score is 
 0.9963636363636363


c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [6]:
obj=SVC(kernel='rbf')
obj.fit(x_train,y_train)
y_pred=obj.predict(x_test)
from sklearn.metrics import classification_report as cr, confusion_matrix as cm,accuracy_score as asp
result=cr(y_test,y_pred)
result1=cm(y_test,y_pred)
result2=asp(y_test,y_pred)
print(f' the classification_report is \n{result}') 
print(f'the confusion_matrix is \n {result1}')
print(f'the accuracy_score is \n {result2}')

c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


 the classification_report is 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       148
           1       1.00      1.00      1.00       127

    accuracy                           1.00       275
   macro avg       1.00      1.00      1.00       275
weighted avg       1.00      1.00      1.00       275

the confusion_matrix is 
 [[148   0]
 [  0 127]]
the accuracy_score is 
 1.0


In [7]:
obj=SVC(kernel='sigmoid')
obj.fit(x_train,y_train)
y_pred=obj.predict(x_test)
from sklearn.metrics import classification_report as cr, confusion_matrix as cm,accuracy_score as asp
result=cr(y_test,y_pred)
result1=cm(y_test,y_pred)
result2=asp(y_test,y_pred)
print(f' the classification_report is \n{result}') 
print(f'the confusion_matrix is \n {result1}')
print(f'the accuracy_score is \n {result2}')

c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


 the classification_report is 
              precision    recall  f1-score   support

           0       0.57      0.57      0.57       148
           1       0.50      0.49      0.49       127

    accuracy                           0.53       275
   macro avg       0.53      0.53      0.53       275
weighted avg       0.53      0.53      0.53       275

the confusion_matrix is 
 [[85 63]
 [65 62]]
the accuracy_score is 
 0.5345454545454545


##second example

In [24]:
weather=['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny','Sunny',
'Rainy','Sunny','Overcast','Overcast','Rainy']
temp=['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']

play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']
from sklearn import preprocessing as p
le=p.LabelEncoder()
obj=le.fit_transform(weather)
obj1=le.fit_transform(temp)
obj2=le.fit_transform(play)
print(f'weather is \n {obj}')
print(f'temperature is \n {obj1}')
print(f' play is \n {obj2}')

weather is 
 [2 2 0 1 1 1 0 2 2 1 2 0 0 1]
temperature is 
 [1 1 1 2 0 0 0 2 0 2 2 2 1 2]
 play is 
 [0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [30]:
from sklearn import datasets
wine=datasets.load_wine()
from sklearn.model_selection import train_test_split as t
x_train,x_test,y_train,y_test=t(wine.data,wine.target,test_size=0.2,random_state=42)
print(len(x_train))
print(len(x_test))

142
36


In [35]:
from sklearn.naive_bayes import GaussianNB as g
obj=g()
obj.fit(x_train,y_train)
y_pred=obj.predict(x_test)
from sklearn.metrics import accuracy_score as asp
result=asp(y_test,y_pred)
print(f'the accuracy score of naive bayes algorithm is {result}')

the accuracy score of naive bayes algorithm is 1.0
